if [[ -n "${MC_SID:-}" ]]; then
  export skip_global_compinit=1

  PS1='%n@%m:%~%# '
  return
fi

ZSH_CONFIG="$HOME/.zsh_configs"
[ -f "$ZSH_CONFIG/init.zsh" ] && source "$ZSH_CONFIG/init.zsh"


# bun completions
[ -s "/home/jakub/.bun/_bun" ] && source "/home/jakub/.bun/_bun"
